CREATE DATABASE COMPANY;

USE COMPANY;

CREATE TABLE DEPARTMENTS(
	DEPARTMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(255)
);

INSERT INTO DEPARTMENTS(DEPARTMENT_NAME)
VALUES
('HR'),
('FINANCE'),
('IT'),
('MARKETING');

DELIMITER //
CREATE PROCEDURE LIST_DEPARTMENTS()
BEGIN
	DECLARE DEPT_NAME VARCHAR(255);
    DECLARE DONE INT DEFAULT FALSE;
    
    DECLARE DEPT_CURSOR CURSOR FOR
		SELECT DEPARTMENT_NAME FROM DEPARTMENTS;
        
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
    
    OPEN DEPT_CURSOR;
    
    READ_LOOP : LOOP
		FETCH DEPT_CURSOR INTO DEPT_NAME;
        IF DONE THEN
			LEAVE READ_LOOP;
		END IF;
        
        SELECT DEPT_NAME;
	END LOOP;
    
    CLOSE DEPT_CURSOR;
    END //
    DELIMITER ;
    
    CALL LIST_DEPARTMENTS();
    
    DELIMITER //
    CREATE PROCEDURE UPDATE_SALARIES(DEPT VARCHAR(100))
    BEGIN
		DECLARE EMP_ID INT;
        DECLARE CURRENT_SALARY DECIMAL(10,2);
        DECLARE DONE INT DEFAULT FALSE;
        
        DECLARE EMP_CURSOR CURSOR FOR
        SELECT EMPLOYEE_ID,SALARY FROM EMPLOYEES WHERE DEPARTMENT = DEPT;
        
        DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
        
        OPEN EMP_CURSOR;
        
        READ_LOOP : LOOP
			FETCH EMP_CURSOR INTO EMP_ID,CURRENT_SALARY;
            
		IF DONE THEN
			LEAVE READ_LOOP;
		END IF;
        
        UPDATE EMPLOYEES
        SET SALARY = CURRENT_SALARY * 1.10
        WHERE EMPLOYEE_ID = EMP_ID;
        END LOOP;
        
        CLOSE EMP_CURSOR;
        END;
    
    
    