USE MATHS;

CREATE TABLE EMPLOYEES(
	id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    salary DECIMAL(10,2) NOT NULL,
    department_id INT NOT NULL,   
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

DELIMITER //

CREATE PROCEDURE AddEmployee (
IN empName VARCHAR(50),
IN empSalary DECIMAL(10,2),
IN empDeptId INT
)
BEGIN
INSERT INTO employees (name, salary, department_id)
VALUES (empName, empSalary, empDeptId);
END //

DELIMITER ;

CALL AddEmployee('John Doe', 75000.00, 1);

EXAMPLE 1] :

USE FUN;

DELIMITER //
CREATE PROCEDURE ADDITION(IN NUM1 INT,IN NUM2 INT,OUT SUM INT)
BEGIN 
	SET SUM = NUM1 + NUM2;
END //
DELIMITER ;

SET @RESULT = 0;
CALL ADDITION(5,10,@RESULT);
SELECT @RESULT AS SUM;

EXAMPLE 2] :

USE FUN;

CREATE TABLE SALES(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMERID INT,
    AMOUNT DECIMAL(10,2)
);

INSERT INTO SALES(CUSTOMERID,AMOUNT)
VALUES
(1,100),
(1,200),
(2,150),
(2,150);

DELIMITER //
CREATE PROCEDURE TOTAL(IN CUSTOMERID INT,OUT TOTALSALES DECIMAL(10,2))
BEGIN
	SELECT SUM(AMOUNT) INTO TOTALSALES
    FROM SALES
    WHERE CUSTOMERID = CUSTOMERID; 
END //
DELIMITER ;

SET @TOTAL = 0;
CALL TOTAL(1,@TOTAL);
SELECT @TOTAL AS TOTALSALES;

