1] Create table :

CREATE DATABASE STUDENT;

CREATE TABLE `STUDENT`.`INFO`
(
	STUDENT_ID INT,
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    ADDRESS VARCHAR(255)
)

2] Insert data into the table :

CREATE DATABASE STUDENT;

CREATE TABLE `STUDENT`.`INFO`
(
	STUDENT_ID INT,
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    ADDRESS VARCHAR(255)
)

INSERT INTO STUDENT.INFO(STUDENT_ID,FIRSTNAME,LASTNAME,ADDRESS) VALUES(1,'JOHN','DOE','XYZ');
INSERT INTO STUDENT.INFO(STUDENT_ID,FIRSTNAME,LASTNAME,ADDRESS) VALUES(2,'ZAIN','MALIK','ABC');
INSERT INTO STUDENT.INFO(STUDENT_ID,FIRSTNAME,LASTNAME,ADDRESS) VALUES(3,'LUIS','BIBER','LMN');

3] Create table with constraints :

